# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Github Actions Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
       - name: Checkout code
         uses: actions/checkout@v2
         
       - name: Set up JDK 1.8
         uses: actions/setup-java@v1
         with:
           java-version: 1.8
       - name: Build with Maven
         run: mvn -B package --file pom.xml
         
       - name: avoidFailTestOnlyOnMaven
         run: Dsurefire.failIfNoSpecifiedTests=false
         
       - name: RunMavenTest
         # You may pin to the exact commit or the version.
         # uses: Maes95/maven-action@69c270aa2d7d371b74a888e3248af909f840585a
         uses: Maes95/maven-action@1.0.0
         with:
           # If true, build jar of the project
           package: default
           # Test to exclude
